### PR TITLE
Supply missing right parenthesis

### PR DESCRIPTION
**Pull request by ffoulkes**
Two previous attempts to fix this have been blocked because the commits weren't signed.
Third time's a charm?

### CODE REVIEW

**Comment by fruffy** [comment]
Who is currently maintaining target-syslibs? Any designated maintainers?

**Review by fruffy — APPROVED** [review]

**Comment by fruffy** [comment]
> > Who is currently maintaining target-syslibs? Any designated maintainers?
> 
> I don't know, but I'll ask around.

Thanks! I am currently cleaning up the permission on all `p4lang` repositories. I have been also looking at syslibs and whether maintainers need to be removed or added.

**Review by saynb — APPROVED** [review]

**Comment by saynb** [comment]
> Who is currently maintaining target-syslibs? Any designated maintainers?
Right now I am the only maintainer. But let me see if I can get some more people for these repos.

I am not sure why this PR is complaining about parenthesis

**Comment by fruffy** [comment]
> Right now I am the only maintainer. But let me see if I can get some more people for these repos.

Please let me know. In the meantime I will remove everyone else.

**Pull request merged**
